services:
  - type: web
    name: fastapi-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_fast:app --host 0.0.0.0 --port $PORT"
    plan: free
